{% set name = "snowflake-ingest" %}
{% set version = "1.0.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/snowflakedb/snowflake-ingest-python/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 444428588c3ea087a4f065ed1a09d3d8fbd261cbdc0b20684a3b92dc7f80434c

  # Upstream tarball is not packaged properly and so our build fails
  # url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/snowflake_ingest-{{ version }}.tar.gz
  # sha256: f9914503a9eb112ae0335f47c0c7d5a2f69217451a6b958a3201c0582357b1bc

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - cryptography
    - furl
    - pyjwt
    - python >=3.6
    - requests <=2.32.3
    - snowflake-connector-python >=3.0.3

test:
  imports:
    - snowflake.ingest
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.snowflake.net
  summary: Official SnowflakeDB File Ingest SDK
  license: Apache-2.0
  # pr filed https://github.com/snowflakedb/snowflake-ingest-python/pull/51
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
    - xhochy
